# settings for TINAH board
BOARDS_TXT = /Users/Alpha/Documents/Arduino/hardware/TINAH/avr/boards.txt
ARDUINO_CORE_PATH = /Users/Alpha/Documents/Arduino/hardware/TINAH/avr/cores/Arduino
ARDUINO_VAR_PATH = /Users/Alpha/Documents/Arduino/hardware/TINAH/avr/variants
BOARD_TAG = TINAH
AVRDUDE_MCU = atmega128

# libraries to include
ARDUINO_LIBS = phys253TINAHArduino LiquidCrystal

# external make file
include /usr/local/Cellar/arduino-mk/1.5.1/Arduino.mk
