# settings for TINAH board
TINAH_DIR = /Users/Alpha/Documents/Arduino/hardware/TINAH/avr
BOARDS_TXT = $(TINAH_DIR)/boards.txt
ARDUINO_CORE_PATH = $(TINAH_DIR)/cores/Arduino
ARDUINO_VAR_PATH = $(TINAH_DIR)/variants
BOARD_TAG = TINAH
AVRDUDE_MCU = atmega128

# libraries to include
ARDUINO_LIBS = phys253TINAHArduino LiquidCrystal

# external make file
include /usr/local/Cellar/arduino-mk/1.5.1/Arduino.mk
